[profile.default]
libs = ['lib']
src = 'src'
out = 'out'
test = 'test'
cache_path = 'cache'
script = 'script'
solc_version = '0.8.23'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
