// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly BASE_RPC_URL: string;
  readonly BASE_PATCHWORK_OWNER: string;
  readonly BASE_PATCHWORK_ADDRESS: string;
  readonly SEPOLIA_RPC_URL: string;
  readonly SEPOLIA_PATCHWORK_OWNER: string;
  readonly SEPOLIA_PATCHWORK_ADDRESS: string;
  readonly WAGMI_PROJECT_ID: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
